- package.json
Add `start` script referenced into `README`
> [#175918636] add start script

- src/__integrations__/creditCard.devServer.integration.test.ts
- src/assets/json/check.json
- src/index.pug
- src/index.ts
- src/inputcard.pug
- src/inputcard.ts
- src/js/header.ts
- src/js/idpayguard.ts
- src/js/sessiondata.ts
- src/scss/style.scss
This PR create a new index page with a new field to store user's e-mail.
With this change the page with credit card fields are switched in a second screen.
- Create a new page
- Switched the credit card fields in a second screen
- Refactoring of some helpers in "real" typescript
- Modified pupeteer tests
The new flow designed by Jacopo require a specific page to store user's email.
Pupeteer test
> [#176536665] New index page with e-mail field

- openapi/api.yml
- src/__integrations__/pm.ts
- src/__integrations__/pmClient.addWallet.integration.test.ts
This PR proposes a suite of unit tests covering `addWalletUsingPOST` method of PM client.
- Unit test suite for `addWalletUsingPOST`
- Endpoint `wallet` to PM Stub
This PR is required to assert that the PM shows the expected behaviour when POST `wallet` is called via autogenerated client
Suite of unit tests
> [#176615471] Test suite POST wallet

- src/inputcard.ts
This PR drop set & get items in sessionStorage for creditcard's data
I removed set & get from inputcard screen
For now, we couldn't use sessionStorage for this type of data (security reasons).
Pupeteer tests
> [#176819941] Dropped sessionstorage for cc's data

- src/check.pug
- src/check.ts
This PR is useful to show to the user a "checkout page" where all of the data filled are listed in a unique list.
The code are tested by puppeteer & linter.
> [#175798598] Mapping of data stored in SS with the DOM

- openapi/api.yml
- src/__integrations__/pm.ts
- src/__integrations__/pmClient.resources.integration.test.ts
- src/__mocks__/mocks.ts
- src/__mocks__/resources/terms/en/termsAndConditions.txt
- src/__mocks__/resources/terms/it/termsAndConditions.txt
The goal of this PR is to add unit tests for api `v4/resources`
- fix api spec for _pp-restapi/v4/resources_  with correct response produced by payment manager;
- add unit tests (with mock server);
The invocation of the following api (Payment Manager):
- POST `pp-restapi/v4/resources?language=<it|en>`
- yarn test
> NOTE : before typing `yarn install && yarn generate`
> [#176738799] Add resources tests

- src/check.ts
- src/includes/footer.pug
- src/index.ts
- src/inputcard.ts
- src/js/dropdowns.ts
- src/js/header.ts
- src/response.ts
This PR solves the bug of "hidden header" when in mobile viewport
- Removed dummy text
- Refactored dropdown function 
- Created a dropdown helper
To show header in all of the steps of the flow, either when in mobile.
- Linter
> [#176963818] bug header mobile

- openapi/api.yml
- src/__integrations__/docker/pmClient.startSession.integration.docker.test.ts
- src/__integrations__/pm.ts
- src/__integrations__/pmClient.addWallet.integration.test.ts
- src/__integrations__/pmClient.approveTerms.integration.test.ts
- src/inputcard.ts
This PR proposes a fix to local mantained PM specs to align them with the new ones published by the real PM, which have been changed to cope with the new 3DS2 protocol.
- Changed spec of `start-session` endpoint (`data` field in response is no longer required)
- Changed test of `start-session` in docker environment
- Changed test of `startSession`, `addWallet`, `approveTerms`  in integration with a stub of PM
- Changed real call in fronted to start-session
This change is required to fix a breaking change of PM
```
yarn test:docker-int pmClient.startSession
yarn test:integration pmClient.startSession
```
> [#176942427] Fixed spec of startSession

- src/check.pug
This PR fix the url of "edit button" when in checkout page
- edit url
Fix the url of "edit button" when in checkout page
> [#177061721] FIX url edit button on checkout

- src/includes/langselector.pug
- src/includes/modal/securecode.pug
- src/inputcard.pug
- src/inputcard.ts
- src/js/modals.ts
- src/scss/style.scss
This PR is aimed to fix several cosmetic & interaction fixes.
- Inputcard typescript: various changes
- inputcard pug: various changes
- style: variuos changes
> [#177060967] bugfixing inputcard

- src/utils/__test__/transactionHelper.test.ts
- src/utils/transactionHelper.ts
This PR introduces unit tests for two crucial functions in _transactionHelper.ts_:
- `resumeTransactionTask`
- `checkStatusTask`
- Added new test file _transactionHelper.test.ts_
- yarn test transactionHelper.test
> [#IOPAY-5] Added unit tests for transactionHelper

- src/assets/json/psp.json
- src/check.pug
- src/choosepsp.pug
- src/choosepsp.ts
- src/scss/style.scss
This PR is about a page/function to choose another PSP rather then use the "default" one suggested by PM.
- Cosmetic fixes on the page.
- Implementing the call to specific service to obtain the PSP list (To-DO)
A user, after the input of own credit card, could choose a preferred PSP from a list
Linter, Puppeteer
> [#175798637] A user could choose a preferred PSP

- src/choosepsp.ts
- src/response.ts
Description
This PR adds  environment variables defined in `Config` module in `changePsp` and `response` page.
> [IOPAY-36] Added  env variables in ChangePsp and Response page

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- package.json
- Ubuntu image for deploy pipeline
- update app name in package.json
- upgrade node version to 12.19.1 in pipelines
> [IOPAY-32] Refactoring  and Ubuntu image for deploy pipeline

- src/inputcard.ts
Add securityCode in session storage
> [IOPAY-12] Add securityCode in session storage

- src/check.ts
- add tipo = "web" as pay API body param;
- workPhone --> mobilePhone
> [IOPAY-32] fix 3dsdata and tipo param in pay invocation

- src/check.ts
- add constant browserColorDepth
> Iopay 32 fixcolor depth

- .env.local
- src/__integrations__/docker/pmClient.resume.integration.docker.test.ts
- src/__integrations__/pmClient.addWallet.integration.test.ts
- src/__integrations__/pmClient.browser.integration.test.ts
- src/check.ts
- src/choosepsp.ts
- src/inputcard.ts
- src/js/sessiondata.ts
- src/response.ts
- src/utils/mixpanelHelperInit.ts
This PR "real" enable mixpanel configuration
Removed all mocks `mixpanel.track` calls event and replaced with real one.
Have a real  tracking events on [mixpanel](https://mixpanel.com/) in order to create a custom [funnel](https://pagopa.atlassian.net/browse/IOPAY-20)  
Manual test
> [IOPAY-26] enable mixpanel configuration

- .devops/deploy-pipelines.yml
- Update legacy user for CI pipeline: `pagopa -> io-azure-devops-github-ro`;
> [IOPAY-136] Update legacy user for CI pipeline

- src/__integrations__/uat-prod/pmClient.resources.integration.uat-prod.test.ts
- src/utils/transactionHelper.ts
- Added language in _resume_ and _resume3ds2_ API invocation;
- Removed legacy integration tests;
The goal of this PR is to add language in  _resume_ and _resume3ds2_ API invocation in order to solve issue wrong language in notification result mail.
> [IOPAY-144] Add language in resume and resume3ds2

- src/response.pug
- src/response.ts
- src/utils/transactionHelper.ts
- add final status check at the _start of polling;_
- add final status check after _3ds2 method step;_
- add final status check before _3ds2 challenge step;_
The goal of this PR is to check a possible error status during the steps of _3ds2 flow_.
- run app locally;
- run integration tests;
> [IOPAY-166] show final message result

- src/response.ts
- add sessionstorage.clear() in final status result;
The goal of this PR is to clear session storage at the end of payment;
> [IOPAY-166] clear sessionStorage

- src/privacypolicy/index.html
Final text to use in privacy modal
> [#IOPAY-156] Privacy text

- src/cancelled.pug
- src/check.pug
- src/choosepsp.pug
- src/index.pug
- src/inputcard.pug
- src/ko.pug
- src/response.pug
FIX class name to center the error message
> [#IOPAY-185] il messaggio di errore non è centrato

- src/check.ts
- src/choosepsp.pug
- src/choosepsp.ts
- src/includes/footer.pug
- src/inputcard.ts
- src/js/buttonutils.ts
- src/privacypolicy/index.html
- src/response.pug
This PR solves several issues:
#IOPAY-212
#IOPAY-205 
#IOPAY-214 
#IOPAY-206
> [#IOPAY-204] bugs e miglioramenti

- .env.local
- fix local env to disable mixpanel events for local development;
> Disable mixpanel events in local mode

- .devops/pagopa-deploy-pipelines.yml
- src/js/sessiondata.ts
- src/ko.pug
> Add pagopaCommons module

- src/includes/footer.pug
Accessibility statement url in footer
> [#IOPAY-254] Accessibility statement url

- src/utils/mixpanelHelperInit.ts
- add  `property_blacklist` with  ` ["$current_url", "$initial_referrer"]` in mixpanel initial setup.
The goal of this PR is to avoid urls in mixpanel events.
> disable current_url and  in mixpanel events

- src/utils/mixpanelHelperInit.ts
- delete _referrer_ property in mixpanel event
> delete referrer in mixpanel events

- src/response.ts
- src/sessionData/__test__/WalletSession.test.ts
> fix wallet decode

- src/utils/__test__/transactionHelper.test.ts
- src/utils/mixpanelHelperInit.ts
Mixpanel Track function must be loaded in "dev mode" if user doesn't accept Mixpanel cookie
> FIX also track function must depend from OT

- src/utils/mixpanelHelperInit.ts
Mixpanel init on / off must be evaluate also when the banner cookies doesn't pop-up.
- create a new function to check user consent
Mixpanel init on / off must be evaluate also when the banner cookies doesn't pop-up.
> [#IOPAY-372] Mixpanel init if cookie consent presents

- src/inputcard.pug
- src/js/sessiondata.ts
THIS PR solves a not nice bug when a user use the "back button" on the first screen of our webapp
- Use pushState to set an hash to url
- use an event listner to manage a message to user
THIS PR solves a not nice bug when a user use the "back button" on the first screen of our webapp
> [#IOPAY-376] Manage "back button"

- src/index.pug
- src/index.ts
- src/scss/style.scss
This PR adds a new e-mail field in the first page to check user's input
- Added a html field in index.pug
- added a listner on index.ts
- modified the current listner of e-mail field to check values
- modified style according with the designer
Check the user's e-mail
> [#IOPAY-377] Added a new email field to check value

- src/privacypolicy/index.html
Update privacy text as asked by Legal
> [#IOPAY-428] Update privacy text

- src/inputcard.pug
Change label to the privacy button as requested in #IOPAY-434
- change label of privacyTogglerInput
#IOPAY-434
> [#IOPAY-434] FIX btn label privacy

- src/sessionData/PaymentSession.ts
- src/sessionData/__test__/PaymentSession.test.ts
- Make _fiscalCode_, _nomePagatore_ and _codicePagatore_ optional for paymentSession
> [IOPAY-475] Update paymentSession interface

- src/check.ts
- update total amounts in order to include zero commissions;
> [IOPAY-539] fix total amount for donations
